version: '3.5'

services:
  mongo-unsecure:
    container_name: mongo-unsecure
    image: mongo:4.2
    ports:
      - 37027:27017
    #command: mongod
    command: mongod --auth
    # command: mongod --auth
#docker-compose -f docker-compose.yml up -d
#docker container exec -it mongo-unsecure /bin/sh
#docker-compose -f docker-compose.yml stop
#mongo --username mongo --password mongo
